### ISSUE TITLE
File blocked after usage of ImageScaling.Read(filepath)

### ISSUE THREAD

**Issue by svenclemens** [CompuMasterGmbH/CompuMaster.Imaging#1]
It seems that an ImageScaling-object doesn't release the created filehandle after loading the file.
If this is intentionally there should be a way to close the handle after usage, which is lacking at the moment.

Also it may be a good idea to implement the IDisposable interface, which could ensure all handles are closed and disposed if called.

Currently have to use ImageScaling.Read(byte()) to ensure file is deletable after loading.

**Comment by jochenwezel** [comment]
Great that you found this issue! :-)
Let me know when I shall push the latest version (after your bugfix patch) to NuGet

**Comment by svenclemens** [comment]
Just implemented  IDisposable.
Handles and ressources can now get released by calling Dispose()
